In [3]:
from pprint import pprint
import time
import numpy as np
import pandas as pd
import getpass
from ..src import parsing_class
ETHtweets =  crypto_csv_tweets(f"/media/{getpass.getuser()}/extra/Crypto-Capstone-1/data/ETH-tweets/ETHtweets.csv")
BTCtweets = crypto_csv_tweets(f"/media/{getpass.getuser()}/extra/Crypto-Capstone-1/data/BTC-tweets/BTC.csv")

ValueError: attempted relative import beyond top-level package

In [11]:
BTCtweets.data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4897156 entries, 0 to 4897155
Data columns (total 23 columns):
tweet_id                  int64
conversation_id           int64
author_id                 int64
author_name               object
isverified                int64
datetime                  object
language                  object
tweet_text                object
replies                   int64
retweets                  int64
favorites                 int64
mentions                  object
hashtags                  object
permalink                 object
urls                      object
ispartofconversation      int64
isreply                   int64
isretweet                 int64
reply_to_user_id          float64
reply_to_user_name        object
quoted_tweet_id           float64
quoted_tweet_user_name    object
quoted_tweet_user_id      float64
dtypes: float64(3), int64(10), object(10)
memory usage: 859.3+ MB

In [12]:
BTCtweets.data.head()

,tweet_id,conversation_id,author_id,author_name,isverified,datetime,language,tweet_text,replies,retweets,...,permalink,urls,ispartofconversation,isreply,isretweet,reply_to_user_id,reply_to_user_name,quoted_tweet_id,quoted_tweet_user_name,quoted_tweet_user_id
0,1049449336726122497,1049449336726122497,767253595716661248,sirarthur04,0,2018-10-08,und,#BitcoinOne #BTCONE #Bounty #Bitcoin #Ethereum...,0,0,...,/sirarthur04/status/1049449336726122497,https://twitter.com/THEBITCOINONE/status/10493...,0,0,1,NaN,NaN,1.049322e+18,THEBITCOINONE,9.416432e+17
1,1049449307043024896,1049449307043024896,768679436,tapatrade,0,2018-10-08,und,#bitcoin https://twitter.com/MustStopMurad/sta...,0,0,...,/tapatrade/status/1049449307043024896,https://twitter.com/MustStopMurad/status/10221...,0,0,1,NaN,NaN,1.022170e+18,MustStopMurad,8.443046e+17
2,1049449278194769920,1049449278194769920,808146374,AutolottoscratR,0,2018-10-08,und,#Autolottoscratchr #autolotto #worldsfirstscra...,0,0,...,/AutolottoscratR/status/1049449278194769920,https://www.instagram.com/p/BosQITMHHsa/?utm_s...,0,0,0,NaN,NaN,NaN,NaN,NaN
3,1049449198771470336,1049449198771470336,849237156010786819,otc_cyborg,0,2018-10-08,en,UK Telecoms Regulator Receives Grant to Deploy...,0,0,...,/otc_cyborg/status/1049449198771470336,https://ift.tt/2Og4951,0,0,0,NaN,NaN,NaN,NaN,NaN
4,1049449160129343488,1049449160129343488,1466726246,Coinboard,0,2018-10-08,en,Electron Cash Developer Reveals In-Wallet BCH ...,0,0,...,/Coinboard/status/1049449160129343488,http://twib.in/l/9MKRadjK6Mod,0,0,0,NaN,NaN,NaN,NaN,NaN

In [13]:
BTCtweets.data.describe()

,tweet_id,conversation_id,author_id,isverified,replies,retweets,favorites,ispartofconversation,isreply,isretweet,reply_to_user_id,quoted_tweet_id,quoted_tweet_user_id
count,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,4.897156e+06,1.175450e+05,4.210900e+05,4.210900e+05
mean,9.799385e+17,9.798617e+17,4.354351e+17,1.551819e-02,3.891969e-01,1.413259e+00,2.426264e+00,3.186135e-02,2.511621e-02,9.230071e-02,3.247818e+17,9.938126e+17,6.793604e+17
std,3.890705e+16,3.908563e+16,4.535875e+17,1.236017e-01,1.302262e+01,2.923208e+01,3.321360e+01,1.756309e-01,1.564781e-01,2.894500e-01,4.383222e+17,4.088153e+16,4.194951e+17
min,9.170303e+17,3.148255e+08,2.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e+01,9.800000e+01,1.200000e+01
25%,9.453107e+17,9.452870e+17,1.093161e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.187564e+08,9.732427e+17,3.160617e+09
50%,9.767369e+17,9.767077e+17,4.329154e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.207129e+09,1.000434e+18,9.274561e+17
75%,1.016667e+18,1.016642e+18,9.180179e+17,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.877480e+17,1.020983e+18,9.630886e+17
max,1.049449e+18,1.049449e+18,1.049447e+18,1.000000e+00,6.183000e+03,1.683800e+04,1.964700e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.047477e+18,1.049442e+18,1.048881e+18

In [5]:
ETHtweets.data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3758572 entries, 0 to 3758571
Data columns (total 22 columns):
tweet_id                  int64
conversation_id           int64
author_id                 int64
author_name               object
isverified                int64
datetime                  object
tweet_text                object
replies                   int64
retweets                  int64
favorites                 int64
mentions                  object
hashtags                  object
permalink                 object
urls                      object
ispartofconversation      int64
isreply                   int64
isretweet                 int64
reply_to_user_id          float64
reply_to_user_name        object
quoted_tweet_id           float64
quoted_tweet_user_name    object
quoted_tweet_user_id      float64
dtypes: float64(3), int64(10), object(9)
memory usage: 630.9+ MB

In [14]:
ETHtweets.data.head()

,tweet_id,conversation_id,author_id,author_name,isverified,datetime,tweet_text,replies,retweets,favorites,...,permalink,urls,ispartofconversation,isreply,isretweet,reply_to_user_id,reply_to_user_name,quoted_tweet_id,quoted_tweet_user_name,quoted_tweet_user_id
0,1024444451639451653,1024444451639451653,2276587183,coinspectator,0,2018-07-31,Shopin Continues to Make Blockchain History: P...,0,0,0,...,/coinspectator/status/1024444451639451653,https://coinspectator.com/news/684586/shopin-c...,0,0,0,NaN,NaN,NaN,NaN,NaN
1,1024444283363962880,1024444283363962880,963657116782419970,drewawise,1,2018-07-31,You must see this video about #TRON $ trx #btc...,0,4,12,...,/drewawise/status/1024444283363962880,https://twitter.com/justinsuntron/status/10242...,0,0,1,NaN,NaN,1.024226e+18,justinsuntron,9.028390e+17
2,1024444257116057600,1024444257116057600,259856497,BeerdHead,0,2018-07-31,Dear all of $ Crypto Let HIM HEAR IT Hope My M...,1,0,3,...,/BeerdHead/status/1024444257116057600,https://twitter.com/RudyHavenstein/status/1024...,0,0,1,NaN,NaN,1.024442e+18,RudyHavenstein,1.358146e+09
3,1024444244830969857,1024444244830969857,46092203,maransa2006,0,2018-07-31,"This tweet; ""TOP 10 PRICES DECEMBER Show you'r...",0,0,0,...,/maransa2006/status/1024444244830969857,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN
4,1024444219778203650,1024444219778203650,953111456332984321,CereloMasilag,0,2018-07-31,CYDER Token Telegram Airdrop we are airdroping...,0,0,0,...,/CereloMasilag/status/1024444219778203650,https://telegram.me/Cyder_token_bot,0,0,0,NaN,NaN,NaN,NaN,NaN

In [15]:
ETHtweets.data.describe()

,tweet_id,conversation_id,author_id,isverified,replies,retweets,favorites,ispartofconversation,isreply,isretweet,reply_to_user_id,quoted_tweet_id,quoted_tweet_user_id
count,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,3.758572e+06,7.153300e+04,6.410490e+05,6.410490e+05
mean,9.573853e+17,9.573448e+17,5.133036e+17,9.846559e-03,4.769051e-01,2.474671e+00,2.870640e+00,2.278046e-02,1.986792e-02,1.880922e-01,5.427760e+17,9.849443e+17,8.066762e+17
std,6.744656e+16,6.748275e+16,4.476774e+17,9.874010e-02,2.143572e+01,5.248792e+01,4.860418e+01,1.492029e-01,1.395464e-01,3.907858e-01,4.623968e+17,3.974830e+16,3.293228e+17
min,6.272719e+17,6.402164e+16,2.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e+01,7.800000e+01,1.200000e+01
25%,9.394280e+17,9.393882e+17,2.232163e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.614454e+08,9.772231e+17,8.978274e+17
50%,9.791352e+17,9.790990e+17,7.826293e+17,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.762862e+17,9.932696e+17,9.336415e+17
75%,1.000220e+18,1.000198e+18,9.321333e+17,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.588147e+17,1.005400e+18,9.622931e+17
max,1.024444e+18,1.024444e+18,1.024346e+18,1.000000e+00,1.130800e+04,1.839000e+04,1.637500e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.023806e+18,1.024442e+18,1.023731e+18

In [16]:
BTCtweets.print_min_max_datetime()

The oldest tweet is: 2017-10-08
The youngest tweet is: 2018-10-08

In [9]:
ETHtweets.print_min_max_datetime()

The oldest tweet is: 2015-07-31
The youngest tweet is: 2018-07-31

In [10]:
BTCtweets.date_filter('2017-10-08','2018-02-10')

TypeError: '>' not supported between instances of 'datetime.date' and 'str'

In [ ]:
BTCtweets.data.head()